version: '3'

services:
  #  elasticsearch:
  #    container_name: elasticsearch
  #    image: xiaoxuan6/elasticsearch:7.17.6
  #    restart: on-failure
  #    ports:
  #      - 9200:9200
  #    environment:
  #      - TZ=$TZ
  #      - discovery.type=single-node
  #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    volumes:
  #      - ./elasticsearch/data:/usr/share/elasticsearch/data
  #      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #    networks:
  #      dnmp:

  #  kibana:
  #    container_name: kibana
  #    image: kibana:7.17.6
  #    ports:
  #      - 5601:5601
  #    restart: on-failure
  #    depends_on:
  #      - elasticsearch
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #    networks:
  #      dnmp:

  php:
    container_name: php
    image: xiaoxuan6/php:7.4-fpm-alpine
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    networks:
      dnmp:

  mysql:
    container_name: mysql
    image: mysql:5.7.40
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      dnmp:

  #  redis:
  #    container_name: redis
  #    image: redis
  #    ports:
  #      - 6379:6379
  #    networks:
  #      dnmp:

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      dnmp:

  artisan:
    container_name: artisan
    image: xiaoxuan6/php:7.4-fpm-alpine
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      dnmp:

networks:
  dnmp: