version: '3.6'

services:
  #  elasticsearch:
  #    container_name: elasticsearch
  #    image: xiaoxuan6/elasticsearch:7.17.6
  #    restart: on-failure
  #    ports:
  #      - 9200:9200
  #    environment:
  #      - TZ=$TZ
  #      - discovery.type=single-node
  #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    volumes:
  #      - ./elasticsearch/data:/usr/share/elasticsearch/data
  #      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #    networks:
  #      damp:

  #  kibana:
  #    container_name: kibana
  #    image: kibana:7.17.6
  #    ports:
  #      - 5601:5601
  #    restart: on-failure
  #    depends_on:
  #      - elasticsearch
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #    networks:
  #      damp:

  mysql:
    container_name: mysql
    image: mysql:5.7.40
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      damp:

  #  redis:
  #    container_name: redis
  #    image: redis
  #    ports:
  #      - 6379:6379
  #    networks:
  #      damp:

  app:
    container_name: app
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/apache2/sites-available/000-default.conf
      - ./entrypoint.sh:/usr/local/bin/entrypoint
    depends_on:
      - mysql
    networks:
      damp:

networks:
  damp: